server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/big-tomcat/tensquare_dev.git
  rabbitmq:
    host: 192.168.81.132
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh